### ISSUE TITLE
Simple CI/CD for sandbox environment

### ISSUE THREAD

**Issue by bedatse** [palo-it-hk/dev-experience#14]
# Key Questions
1. Developer Testing
2. What should be in Integration / Deployment
3. What should happens before/after integration and deployment

# Tasks
- [ ] NodeJS Application Testing / Integration
- [ ] API Contract Testing
- [ ] Frontend Component Testing
- [ ] Provision Linux VM on Azure
- [ ] Linux Configuration Management
- [ ] NodeJS Application Deployment on Linux
- [ ] Deployment Testing / End-to-end Testing
- [ ] Logging
- [ ] Monitoring
